# API Keys
OPENAI_API_KEY = "sk-your-key-here"

[slack]
bot_token = "xoxb-your-bot-token-here"
app_token = "xapp-your-app-token-here"

# Google Configuration
GOOGLE_API_KEY = "your-google-api-key-here"
GOOGLE_CSE_ID = "your-custom-search-engine-id-here" 